const Track = require('./Track')
const  { Talk, _ } = require('./Talk')
const settings = require('./defaultTrackSettings')

function createTestTrack() {
    return new Track('TestTrack', settings)
}

describe('constructor', () => {
    describe('does not throw', () => {
        test('when called with valid settings', () => {
            expect(() => createTestTrack).not.toThrow()
        })
    })
})

describe('isSatisfied', () => {
    describe('returns false', () => {
        test('for empty Track', () => {
            const track = createTestTrack()
            expect(track.isSatisfied).toBe(false)
        })
        test('for Track with single Talk', () => {
            const track = createTestTrack()
            const halfHourTalk = new Talk('Basic Arithmetics', 30)
            track.tryAdd(halfHourTalk)
            expect(track.isSatisfied).toBe(false)
        })
        test('when both Sessions are not satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 120)
            const afterNoonTalk = new Talk('Basic Arithmetics', 120)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isSatisfied).toBe(false)
        })
        test('when only the morning Session is satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 120)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isSatisfied).toBe(false)
        })
        test('when only the afternoon Session is satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 120)
            const afterNoonTalk = new Talk('Basic Arithmetics', 180)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isSatisfied).toBe(false)
        })
    })
    describe('returns true', () => {
        test('when both Sessions are satisfied but not maxed out', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 180)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isSatisfied).toBe(true)
        })
        test('when both Sessions are satisfied and maxed out', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 240)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isSatisfied).toBe(true)
        })
    })
})

describe('isMaxedOut', () => {
    describe('returns false', () => {
        test('for empty Track', () => {
            const track = createTestTrack()
            expect(track.isMaxedOut).toBe(false)
        })
        test('for Track with single Talk', () => {
            const track = createTestTrack()
            const halfHourTalk = new Talk('Basic Arithmetics', 30)
            track.tryAdd(halfHourTalk)
            expect(track.isMaxedOut).toBe(false)
        })
        test('when both Sessions are not satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 120)
            const afterNoonTalk = new Talk('Basic Arithmetics', 120)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(false)
        })
        test('when only the morning Session is satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 120)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(false)
        })
        test('when only the afternoon Session is satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 120)
            const afterNoonTalk = new Talk('Basic Arithmetics', 180)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(false)
        })
        test('when the afternoon Session is exactly satisfied', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 180)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(false)
        })
        test('when the afternoon Session is more than satisfied but not maxed out', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 220)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(false)
        })
    })
    describe('returns true', () => {
        test('when both Sessions are maxed out', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 240)
            track.tryAdd(morningTalk)
            track.tryAdd(afterNoonTalk)
            expect(track.isMaxedOut).toBe(true)
        })
    })
})

describe('talks', () => {
    describe('returns empty list', () => {
        test('for new Track', () => {
            const track = createTestTrack()
            expect(track.talks.length).toBe(0)
        })
        test('after failing to add Talk', () => {
            const track = createTestTrack()
            const tooLongTalk = new Talk('The Importance of Reading The Manual', 360)
            track.tryAdd(tooLongTalk)
            expect(track.talks.length).toBe(0)
        })
    })
    describe('lists all added Talks', () => {
        test('for one added Talk', () => {
            const track = createTestTrack()
            const talk = new Talk('Enjoying being alone', 60)
            track.tryAdd(talk)
            expect(track.talks).toContain(talk)
        })
        test('for many added Talks', () => {
            const track = createTestTrack()
            const firstTalk = new Talk('Being Early', 60)
            const secondTalk = new Talk('The Golden Middle', 60)
            const thirdTalk = new Talk('Being Last', 60)
            track.tryAdd(firstTalk)
            track.tryAdd(secondTalk)
            track.tryAdd(thirdTalk)
            expect(track.talks).toContain(firstTalk)
            expect(track.talks).toContain(secondTalk)
            expect(track.talks).toContain(thirdTalk)
        })
        test('after trying to overfill the Track', () => {
            const track = createTestTrack()
            const firstTalk = new Talk('Being Early', 180)
            const secondTalk = new Talk('The Golden Middle', 120)
            const thirdTalk = new Talk('Being Last', 120)
            const fourthTalk = new Talk('Being Too Late', 120)
            track.tryAdd(firstTalk)
            track.tryAdd(secondTalk)
            track.tryAdd(thirdTalk)
            track.tryAdd(fourthTalk)
            expect(track.talks).toContain(firstTalk)
            expect(track.talks).toContain(secondTalk)
            expect(track.talks).toContain(thirdTalk)
            expect(track.talks).not.toContain(fourthTalk)
        })
    })
})

describe('tryAdd', () => {
    describe('returns true and adds Talk', () => {
        test('for Talk that does not max out any Sessions', () => {
            const track = createTestTrack()
            const talk = new Talk('Basic Arithmetics', 60)
            const succeeded = track.tryAdd(talk)
            expect(succeeded).toBe(true)
            expect(track.talks).toContain(talk)
        })
        test('for multiple Talks that do not max out any Sessions', () => {
            const track = createTestTrack()
            const firstTalk = new Talk('Basic Arithmetics', 60)
            const secondTalk = new Talk('Basic Arithmetics', 60)
            const thirdTalk = new Talk('Basic Arithmetics', 60)
            let succeeded = track.tryAdd(firstTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(secondTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(thirdTalk)
            expect(succeeded).toBe(true)
            expect(track.talks).toContain(firstTalk)
            expect(track.talks).toContain(secondTalk)
            expect(track.talks).toContain(thirdTalk)
        })
        test('for Talk that maxes out the morning Session', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const succeeded = track.tryAdd(morningTalk)
            expect(succeeded).toBe(true)
            expect(track.talks).toContain(morningTalk)
        })
        test('for Talk that maxes out the afternoon Session', () => {
            const track = createTestTrack()
            const afterNoonTalk = new Talk('Basic Arithmetics', 240)
            const succeeded = track.tryAdd(afterNoonTalk)
            expect(succeeded).toBe(true)
            expect(track.talks).toContain(afterNoonTalk)
        })
        test('for two Talks that max out morning and afternoon Sessions', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Basic Arithmetics', 180)
            const afterNoonTalk = new Talk('Basic Arithmetics', 240)
            let succeeded = track.tryAdd(morningTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(afterNoonTalk)
            expect(succeeded).toBe(true)
            expect(track.talks).toContain(morningTalk)
            expect(track.talks).toContain(afterNoonTalk)
        })
    })
    describe('returns false and does not add Talk', () => {
        test('for Talk that is too long for both morning and afternoon Sessions', () => {
            const track = createTestTrack()
            const tooLongTalk = new Talk('The Importance of Reading The Manual', 360)
            let succeeded = track.tryAdd(tooLongTalk)
            expect(succeeded).toBe(false)
            expect(track.talks.length).toBe(0)
        })
        test('for Talk that is too long for morning if afternoon is already maxed out', () => {
            const track = createTestTrack()
            const afterNoonTalk = new Talk('Taking up all the Time', 240)
            let succeeded = track.tryAdd(afterNoonTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(afterNoonTalk)
            expect(succeeded).toBe(false)
            expect(track.talks.length).toBe(1)
        })
        test('for the first Talk that would overfill the Track in the morning', () => {
            const track = createTestTrack()
            const afterNoonTalk = new Talk('Taking up all the Time', 240)
            track.tryAdd(afterNoonTalk)
            const eightyMinuteTalk = new Talk('Basic Arithmetics', 80)
            let succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(false)
            expect(track.talks.length).toBe(3)
        })
        test('for the first Talk that would overfill the Track in the afternoon', () => {
            const track = createTestTrack()
            const morningTalk = new Talk('Taking up all the Time', 180)
            track.tryAdd(morningTalk)
            const eightyMinuteTalk = new Talk('Basic Arithmetics', 80)
            let succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(true)
            succeeded = track.tryAdd(eightyMinuteTalk)
            expect(succeeded).toBe(false)
            expect(track.talks.length).toBe(4)
        })
    })
})
